name: Minify Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          maxdepth: 2

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto-minified JS"
          branch: ${{ github.head_ref }}
